CREATE DATABASE PROYECTO1_REDES

USE PROYECTO1_REDES


CREATE SCHEMA USUARIO

DROP TABLE USUARIO.CUENTA

CREATE TABLE USUARIO.tb_CUENTA
(
	ID_USUARIO INT NOT NULL IDENTITY(1,1) PRIMARY KEY
	, NOMBRE_USUARIO VARCHAR(25) NOT NULL
	, CONTRASENIA_USUARIO VARCHAR(60) NOT NULL
)


ALTER PROCEDURE sp_INSERT_CUENTA
@_NOMBRE VARCHAR(25), @_CONTRASENIA VARCHAR(60)
AS
BEGIN
	DECLARE @local_EXISTS INT = (SELECT
									COUNT(ID_USUARIO)
								FROM USUARIO.tb_CUENTA
								WHERE NOMBRE_USUARIO = @_NOMBRE)

	IF (@local_EXISTS != 0)
	BEGIN
		SELECT 'USUARIO YA EXISTE' AS RESPUESTA
	END
	ELSE
	BEGIN
		INSERT INTO USUARIO.tb_CUENTA
		(
			NOMBRE_USUARIO
			, CONTRASENIA_USUARIO
		)
		VALUES
		(@_NOMBRE, @_CONTRASENIA)
		SELECT 'LISTO' AS RESPUESTA
	END

END

ALTER PROCEDURE sp_INICIAR_SESION
@_NOMBRE VARCHAR(25), @_CONTRASENIA VARCHAR(60)
AS
BEGIN
	DECLARE @local_EXISTS INT = (SELECT
									COUNT(ID_USUARIO)
								FROM USUARIO.tb_CUENTA
								WHERE NOMBRE_USUARIO = 'Fabricio')
	SELECT @local_EXISTS

	IF (@local_EXISTS = 0)
	BEGIN
		SELECT 'USUARIO NO EXISTE' AS RESPUESTA
	END
	ELSE
	BEGIN
		DECLARE @local_CONTRASENIA INT = (SELECT
											COUNT(ID_USUARIO)
										FROM USUARIO.tb_CUENTA
										WHERE CONTRASENIA_USUARIO = @_CONTRASENIA)
		IF(@local_CONTRASENIA = 0)
		BEGIN
			SELECT 'USUARIO Y CONTRASEÑA NO COINCIDEN' AS RESPUESTA
		END
		ELSE
		BEGIN
			DECLARE @local_SESION INT = (SELECT
											ID_USUARIO
										FROM USUARIO.tb_CUENTA
										WHERE NOMBRE_USUARIO = @_NOMBRE AND CONTRASENIA_USUARIO = @_CONTRASENIA)
			IF(@local_SESION IS NOT NULL)
			BEGIN
				SELECT 'SESION INICIADA CON EXITO' AS RESPUESTA
						, @local_SESION AS ID
			END
			ELSE
			BEGIN
				SELECT 'INTENTE DE NUEVO' AS RESPUESTA
			END
			
		END
	END

END